const STUDENTS = {
  LOAD: "STUDENTS_LOAD",
  LOAD_SUCCESS: "STUDENTS_LOAD_SUCCESS",
  LOAD_FAILURE: "STUDENTS_LOAD_FAILURE",
  ADD_STUDENT_REQUEST: "ADD_STUDENT_REQUEST",
  ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
  DELETE_STUDENT_REQUEST: "DELETE_STUDENT_REQUEST",
  EDIT_STUDENT_REQUEST: "EDIT_STUDENT_REQUEST",
  EDIT_STUDENT_REQUEST_SUCCESS: "EDIT_STUDENT_REQUEST_SUCCESS"
};

export { STUDENTS };
